server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: general-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:restaurant
    username: alex
    password: alex
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true

springdoc:
  packages-to-scan: my.company.restaurant

jwt:
  header: Authorization
  secret: secret
  expiration: 1000000